[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#3BD7FF"
backgroundColor = "#070812"
secondaryBackgroundColor = "#131525"
textColor = "#F7F8FF"
font = "sans-serif"
baseRadius = "large"
showWidgetBorder = true
showSidebarBorder = true
chartCategoricalColors = ["#3BD7FF", "#E22DFF", "#FF4F70", "#FF7448", "#72F6C7"]
