[platformio]
default_envs = esp32dev
src_dir = src
include_dir = include
test_dir = test

[env]
test_framework = unity

[env:native]
platform = native
build_src_filter = +<simulated_reader.cpp>
test_build_src = yes

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -D TELEMETRY_SIMULATED=1
lib_deps = bblanchon/ArduinoJson@^7.4.2

[env:esp32dev-pzem]
extends = env:esp32dev
build_flags = -D TELEMETRY_SIMULATED=0
lib_deps =
  ${env:esp32dev.lib_deps}
  https://github.com/mandulaj/PZEM-004T-v30.git#v1.2.1
